//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string Actualizar {
            get {
                return ResourceManager.GetString("Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion.
        /// </summary>
        internal static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Categoria.
        /// </summary>
        internal static string AgregarCategoria {
            get {
                return ResourceManager.GetString("AgregarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar categoría a producto.
        /// </summary>
        internal static string AgregarCATPROD {
            get {
                return ResourceManager.GetString("AgregarCATPROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Dirección.
        /// </summary>
        internal static string AgregarDireccion {
            get {
                return ResourceManager.GetString("AgregarDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Direccion de Envio.
        /// </summary>
        internal static string AgregarDireccionDeEnvio {
            get {
                return ResourceManager.GetString("AgregarDireccionDeEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Direccion de Facturacion.
        /// </summary>
        internal static string AgregarDireccionDeFacturacion {
            get {
                return ResourceManager.GetString("AgregarDireccionDeFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Producto.
        /// </summary>
        internal static string AgregarProducto {
            get {
                return ResourceManager.GetString("AgregarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Stock.
        /// </summary>
        internal static string AgregarStock {
            get {
                return ResourceManager.GetString("AgregarStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Telefono.
        /// </summary>
        internal static string AgregarTelefono {
            get {
                return ResourceManager.GetString("AgregarTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de Usuario.
        /// </summary>
        internal static string AltaUsuario {
            get {
                return ResourceManager.GetString("AltaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un apellido.
        /// </summary>
        internal static string ApellidoVacio {
            get {
                return ResourceManager.GetString("ApellidoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociar Categorías.
        /// </summary>
        internal static string AsociarCategorias {
            get {
                return ResourceManager.GetString("AsociarCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        internal static string Asunto {
            get {
                return ResourceManager.GetString("Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar....
        /// </summary>
        internal static string Buscar1 {
            get {
                return ResourceManager.GetString("Buscar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle.
        /// </summary>
        internal static string Calle {
            get {
                return ResourceManager.GetString("Calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        internal static string CambiarContrasena {
            get {
                return ResourceManager.GetString("CambiarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Estado.
        /// </summary>
        internal static string CambiarEstado {
            get {
                return ResourceManager.GetString("CambiarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de caracteres sobrepasado.
        /// </summary>
        internal static string CaracteresSobrepasado {
            get {
                return ResourceManager.GetString("CaracteresSobrepasado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito vacio.
        /// </summary>
        internal static string CarritoVacio {
            get {
                return ResourceManager.GetString("CarritoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo.
        /// </summary>
        internal static string Catalogo {
            get {
                return ResourceManager.GetString("Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorias.
        /// </summary>
        internal static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías - Productos.
        /// </summary>
        internal static string CategoriasProductos {
            get {
                return ResourceManager.GetString("CategoriasProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        internal static string Clave {
            get {
                return ResourceManager.GetString("Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir Contraseña.
        /// </summary>
        internal static string ClaveRepetida {
            get {
                return ResourceManager.GetString("ClaveRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Area.
        /// </summary>
        internal static string CodigoArea {
            get {
                return ResourceManager.GetString("CodigoArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de Producto.
        /// </summary>
        internal static string CodigoProducto {
            get {
                return ResourceManager.GetString("CodigoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobantes Por Cliente.
        /// </summary>
        internal static string ComprobantesPorCliente {
            get {
                return ResourceManager.GetString("ComprobantesPorCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condicion Fiscal.
        /// </summary>
        internal static string CondicionFiscal {
            get {
                return ResourceManager.GetString("CondicionFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Pedido.
        /// </summary>
        internal static string ConfiirmarPedido {
            get {
                return ResourceManager.GetString("ConfiirmarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion Pago.
        /// </summary>
        internal static string ConfirmacionPago {
            get {
                return ResourceManager.GetString("ConfirmacionPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenidos.
        /// </summary>
        internal static string Contenidos {
            get {
                return ResourceManager.GetString("Contenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña anterior.
        /// </summary>
        internal static string ContrasenaAnterior {
            get {
                return ResourceManager.GetString("ContrasenaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseñas no coinciden, por favor reingréselas.
        /// </summary>
        internal static string ContrasenaNoCoincide {
            get {
                return ResourceManager.GetString("ContrasenaNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string ContrasenasDistintas {
            get {
                return ResourceManager.GetString("ContrasenasDistintas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos 8 carácteres(Mayúscula, Letras y Números).
        /// </summary>
        internal static string ContrasenaSegura {
            get {
                return ResourceManager.GetString("ContrasenaSegura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un correo.
        /// </summary>
        internal static string CorreoVacio {
            get {
                return ResourceManager.GetString("CorreoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotizacion.
        /// </summary>
        internal static string Cotizacion {
            get {
                return ResourceManager.GetString("Cotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta del Empleado.
        /// </summary>
        internal static string CuentaEmpleado {
            get {
                return ResourceManager.GetString("CuentaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la Cuenta.
        /// </summary>
        internal static string DatosCuenta {
            get {
                return ResourceManager.GetString("DatosCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de tarjetas.
        /// </summary>
        internal static string DatosDeTarjetas {
            get {
                return ResourceManager.GetString("DatosDeTarjetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        internal static string DatosPersonales {
            get {
                return ResourceManager.GetString("DatosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo contiene demasiados caracteres..
        /// </summary>
        internal static string DemasiadosCaracteresIngresados {
            get {
                return ResourceManager.GetString("DemasiadosCaracteresIngresados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        internal static string Departamento {
            get {
                return ResourceManager.GetString("Departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion de Categoria.
        /// </summary>
        internal static string DescripcionCategoria {
            get {
                return ResourceManager.GetString("DescripcionCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion de Producto.
        /// </summary>
        internal static string DescripcionProducto {
            get {
                return ResourceManager.GetString("DescripcionProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desear.
        /// </summary>
        internal static string Desear {
            get {
                return ResourceManager.GetString("Desear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deseos.
        /// </summary>
        internal static string Deseos {
            get {
                return ResourceManager.GetString("Deseos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destacados de la semana.
        /// </summary>
        internal static string Destacados {
            get {
                return ResourceManager.GetString("Destacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        internal static string Detalle {
            get {
                return ResourceManager.GetString("Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Factura.
        /// </summary>
        internal static string DetalleFactura {
            get {
                return ResourceManager.GetString("DetalleFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de nota de crédito.
        /// </summary>
        internal static string DetalleNC {
            get {
                return ResourceManager.GetString("DetalleNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Pedido.
        /// </summary>
        internal static string DetallePedido {
            get {
                return ResourceManager.GetString("DetallePedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion de Facturacion.
        /// </summary>
        internal static string DireccionDeFacturacion {
            get {
                return ResourceManager.GetString("DireccionDeFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direcciones de Envio.
        /// </summary>
        internal static string DireccionesDeEnvio {
            get {
                return ResourceManager.GetString("DireccionesDeEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direcciones de Usuario.
        /// </summary>
        internal static string DireccionesDeUsuario {
            get {
                return ResourceManager.GetString("DireccionesDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad.
        /// </summary>
        internal static string Disponibilidad {
            get {
                return ResourceManager.GetString("Disponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un DNI o CUIT.
        /// </summary>
        internal static string DNICUITVacio {
            get {
                return ResourceManager.GetString("DNICUITVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI o CUIT.
        /// </summary>
        internal static string DNIOCUIT {
            get {
                return ResourceManager.GetString("DNIOCUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Cliente: .
        /// </summary>
        internal static string EditarCliente {
            get {
                return ResourceManager.GetString("EditarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Empleado:.
        /// </summary>
        internal static string EditarEmpleado {
            get {
                return ResourceManager.GetString("EditarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ejemplo@gmail.com.
        /// </summary>
        internal static string EjemploCorreo {
            get {
                return ResourceManager.GetString("EjemploCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ej: Departamento &quot;A&quot;.
        /// </summary>
        internal static string EjemploDepto {
            get {
                return ResourceManager.GetString("EjemploDepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ej: Primer piso.
        /// </summary>
        internal static string EjemploPiso {
            get {
                return ResourceManager.GetString("EjemploPiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario/s.
        /// </summary>
        internal static string EliminarUsuario {
            get {
                return ResourceManager.GetString("EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El producto.
        /// </summary>
        internal static string ElProducto {
            get {
                return ResourceManager.GetString("ElProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        internal static string Empleados {
            get {
                return ResourceManager.GetString("Empleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Datos.
        /// </summary>
        internal static string EnviarDatos {
            get {
                return ResourceManager.GetString("EnviarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo a todo el Pais.
        /// </summary>
        internal static string EnvioTodoPais {
            get {
                return ResourceManager.GetString("EnvioTodoPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string Espanol {
            get {
                return ResourceManager.GetString("Espanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Pedido.
        /// </summary>
        internal static string EstadoPedido {
            get {
                return ResourceManager.GetString("EstadoPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo estimado de entrega 3 a 5 dias..
        /// </summary>
        internal static string EstimacionEnvio {
            get {
                return ResourceManager.GetString("EstimacionEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas.
        /// </summary>
        internal static string Facturas {
            get {
                return ResourceManager.GetString("Facturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas de Clientes.
        /// </summary>
        internal static string FacturasCliente {
            get {
                return ResourceManager.GetString("FacturasCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Factura.
        /// </summary>
        internal static string FechaFactura {
            get {
                return ResourceManager.GetString("FechaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de NC.
        /// </summary>
        internal static string FechaNC {
            get {
                return ResourceManager.GetString("FechaNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Pedido.
        /// </summary>
        internal static string FechaPedido {
            get {
                return ResourceManager.GetString("FechaPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Felicitaciones.
        /// </summary>
        internal static string Felicitaciones {
            get {
                return ResourceManager.GetString("Felicitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Envio.
        /// </summary>
        internal static string FormaDeEnvio {
            get {
                return ResourceManager.GetString("FormaDeEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Pago.
        /// </summary>
        internal static string FormaPago {
            get {
                return ResourceManager.GetString("FormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        internal static string Generar {
            get {
                return ResourceManager.GetString("Generar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar NC.
        /// </summary>
        internal static string GenerarNC {
            get {
                return ResourceManager.GetString("GenerarNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar ND.
        /// </summary>
        internal static string GenerarND {
            get {
                return ResourceManager.GetString("GenerarND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Contenidos.
        /// </summary>
        internal static string GestionContenidos {
            get {
                return ResourceManager.GetString("GestionContenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Pedidos.
        /// </summary>
        internal static string GestionPedidos {
            get {
                return ResourceManager.GetString("GestionPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Stock -.
        /// </summary>
        internal static string GestionStock {
            get {
                return ResourceManager.GetString("GestionStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de Categoría.
        /// </summary>
        internal static string IdCategoria {
            get {
                return ResourceManager.GetString("IdCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de Producto.
        /// </summary>
        internal static string IdProducto {
            get {
                return ResourceManager.GetString("IdProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar la calle.
        /// </summary>
        internal static string IngresarCalle {
            get {
                return ResourceManager.GetString("IngresarCalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la contraseña.
        /// </summary>
        internal static string IngresarContrasena {
            get {
                return ResourceManager.GetString("IngresarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la localidad.
        /// </summary>
        internal static string IngresarLocalidad {
            get {
                return ResourceManager.GetString("IngresarLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar el número de la calle.
        /// </summary>
        internal static string IngresarNumeroCalle {
            get {
                return ResourceManager.GetString("IngresarNumeroCalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese solo letras.
        /// </summary>
        internal static string IngresarSoloLetras {
            get {
                return ResourceManager.GetString("IngresarSoloLetras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese solo números.
        /// </summary>
        internal static string IngresarSoloNumeros {
            get {
                return ResourceManager.GetString("IngresarSoloNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese nombre de usuario.
        /// </summary>
        internal static string IngresarUsuario {
            get {
                return ResourceManager.GetString("IngresarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la calle.
        /// </summary>
        internal static string IngreseCalle {
            get {
                return ResourceManager.GetString("IngreseCalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la localidad.
        /// </summary>
        internal static string IngreseLocalidad {
            get {
                return ResourceManager.GetString("IngreseLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el número de la calle.
        /// </summary>
        internal static string IngreseNumero {
            get {
                return ResourceManager.GetString("IngreseNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máximo de 30 caracteres.
        /// </summary>
        internal static string IngresoMax30 {
            get {
                return ResourceManager.GetString("IngresoMax30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese entre 8 y 12 números.
        /// </summary>
        internal static string IngresoSolo8y12 {
            get {
                return ResourceManager.GetString("IngresoSolo8y12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a Pedidos.
        /// </summary>
        internal static string IrAPedidos {
            get {
                return ResourceManager.GetString("IrAPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string Limpiar {
            get {
                return ResourceManager.GetString("Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Deseos.
        /// </summary>
        internal static string ListaDeseos {
            get {
                return ResourceManager.GetString("ListaDeseos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        internal static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail de Empresa.
        /// </summary>
        internal static string MailEmpresa {
            get {
                return ResourceManager.GetString("MailEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapa Del Sitio.
        /// </summary>
        internal static string MapaDelSitio {
            get {
                return ResourceManager.GetString("MapaDelSitio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        internal static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos mas vendidos.
        /// </summary>
        internal static string MasVendidos {
            get {
                return ResourceManager.GetString("MasVendidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medios de Pago:.
        /// </summary>
        internal static string MediosDePago {
            get {
                return ResourceManager.GetString("MediosDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los mejores clientes que nos eligieron.
        /// </summary>
        internal static string MejoresClientes {
            get {
                return ResourceManager.GetString("MejoresClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        internal static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Cuenta.
        /// </summary>
        internal static string MiCuenta {
            get {
                return ResourceManager.GetString("MiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mision.
        /// </summary>
        internal static string Mision {
            get {
                return ResourceManager.GetString("Mision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Contraseña.
        /// </summary>
        internal static string ModificarContrasena {
            get {
                return ResourceManager.GetString("ModificarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar dirección de envío.
        /// </summary>
        internal static string ModificarEnvio {
            get {
                return ResourceManager.GetString("ModificarEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar dirección de facturación.
        /// </summary>
        internal static string ModificarFacturacion {
            get {
                return ResourceManager.GetString("ModificarFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar nombre de usuario.
        /// </summary>
        internal static string ModificarNombreUsuario {
            get {
                return ResourceManager.GetString("ModificarNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Permisos.
        /// </summary>
        internal static string ModificarPermiso {
            get {
                return ResourceManager.GetString("ModificarPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se modificó la contraseña.
        /// </summary>
        internal static string ModificoContrasena {
            get {
                return ResourceManager.GetString("ModificoContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas de crédito de clientes.
        /// </summary>
        internal static string NCClientes {
            get {
                return ResourceManager.GetString("NCClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas de débito de clientes.
        /// </summary>
        internal static string NDClientes {
            get {
                return ResourceManager.GetString("NDClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de nota de débito.
        /// </summary>
        internal static string NDDetalle {
            get {
                return ResourceManager.GetString("NDDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha ND.
        /// </summary>
        internal static string NDFecha {
            get {
                return ResourceManager.GetString("NDFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número ND.
        /// </summary>
        internal static string NDNumero {
            get {
                return ResourceManager.GetString("NDNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Empresa.
        /// </summary>
        internal static string NombreEmpresa {
            get {
                return ResourceManager.GetString("NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Usuario.
        /// </summary>
        internal static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un nombre.
        /// </summary>
        internal static string NombreVacio {
            get {
                return ResourceManager.GetString("NombreVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas de crédito.
        /// </summary>
        internal static string NotasDeCredito {
            get {
                return ResourceManager.GetString("NotasDeCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas de débito.
        /// </summary>
        internal static string NotasDeDebito {
            get {
                return ResourceManager.GetString("NotasDeDebito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestros Clientes.
        /// </summary>
        internal static string NuestrosClientes {
            get {
                return ResourceManager.GetString("NuestrosClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        internal static string NuevaContrasena {
            get {
                return ResourceManager.GetString("NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero.
        /// </summary>
        internal static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Factura.
        /// </summary>
        internal static string NumeroFactura {
            get {
                return ResourceManager.GetString("NumeroFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de NC.
        /// </summary>
        internal static string NumeroNC {
            get {
                return ResourceManager.GetString("NumeroNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Pedido.
        /// </summary>
        internal static string NumeroPedido {
            get {
                return ResourceManager.GetString("NumeroPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener.
        /// </summary>
        internal static string Obtener {
            get {
                return ResourceManager.GetString("Obtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        internal static string Pagar {
            get {
                return ResourceManager.GetString("Pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido.
        /// </summary>
        internal static string Pedido {
            get {
                return ResourceManager.GetString("Pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        internal static string Pedidos {
            get {
                return ResourceManager.GetString("Pedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos Por Cliente.
        /// </summary>
        internal static string PedidosPorCliente {
            get {
                return ResourceManager.GetString("PedidosPorCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        internal static string Permisos {
            get {
                return ResourceManager.GetString("Permisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos de Usuario.
        /// </summary>
        internal static string PermisosUsuario {
            get {
                return ResourceManager.GetString("PermisosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piso.
        /// </summary>
        internal static string Piso {
            get {
                return ResourceManager.GetString("Piso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Politica de Privacidad.
        /// </summary>
        internal static string PoliticaDePrivacidad {
            get {
                return ResourceManager.GetString("PoliticaDePrivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Unitario.
        /// </summary>
        internal static string PrecioUnitario {
            get {
                return ResourceManager.GetString("PrecioUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Predeterminada.
        /// </summary>
        internal static string Predeterminada {
            get {
                return ResourceManager.GetString("Predeterminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   fue correctamente agregado en tu carrito!.
        /// </summary>
        internal static string ProductoCorrectamenteAgregadoAlCarrito {
            get {
                return ResourceManager.GetString("ProductoCorrectamenteAgregadoAlCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        internal static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos en su pedido.
        /// </summary>
        internal static string ProductosEnSuPedido {
            get {
                return ResourceManager.GetString("ProductosEnSuPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        internal static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quienes Somos.
        /// </summary>
        internal static string QuienesSomos {
            get {
                return ResourceManager.GetString("QuienesSomos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordarme.
        /// </summary>
        internal static string Recordarme {
            get {
                return ResourceManager.GetString("Recordarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Empleado.
        /// </summary>
        internal static string RegistrarEmpleado {
            get {
                return ResourceManager.GetString("RegistrarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Cliente.
        /// </summary>
        internal static string RegistroCliente {
            get {
                return ResourceManager.GetString("RegistroCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repita la contraseña.
        /// </summary>
        internal static string RepetirContrasena {
            get {
                return ResourceManager.GetString("RepetirContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repita nueva contraseña.
        /// </summary>
        internal static string RepitaNuevaContrasena {
            get {
                return ResourceManager.GetString("RepitaNuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte.
        /// </summary>
        internal static string Reporte {
            get {
                return ResourceManager.GetString("Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Pedidos Por Fecha.
        /// </summary>
        internal static string ReportePedidosPorFecha {
            get {
                return ResourceManager.GetString("ReportePedidosPorFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Por Usuario.
        /// </summary>
        internal static string ReportePorUsuario {
            get {
                return ResourceManager.GetString("ReportePorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string Reportes {
            get {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen.
        /// </summary>
        internal static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguir Comprando.
        /// </summary>
        internal static string SeguirComprando {
            get {
                return ResourceManager.GetString("SeguirComprando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona Forma de Pago.
        /// </summary>
        internal static string SeleccionaFormadePago {
            get {
                return ResourceManager.GetString("SeleccionaFormadePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simbolo.
        /// </summary>
        internal static string Simbolo {
            get {
                return ResourceManager.GetString("Simbolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar solo letras.
        /// </summary>
        internal static string SoloLetras {
            get {
                return ResourceManager.GetString("SoloLetras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar solo números.
        /// </summary>
        internal static string SoloNumero {
            get {
                return ResourceManager.GetString("SoloNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono de Empresa.
        /// </summary>
        internal static string TelefonoEmpresa {
            get {
                return ResourceManager.GetString("TelefonoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Usuario.
        /// </summary>
        internal static string TipoUsuario {
            get {
                return ResourceManager.GetString("TipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total por Producto.
        /// </summary>
        internal static string TotalPorProducto {
            get {
                return ResourceManager.GetString("TotalPorProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultimos Pedidos.
        /// </summary>
        internal static string UltimosPedidos {
            get {
                return ResourceManager.GetString("UltimosPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se creó el usuario correctamente.
        /// </summary>
        internal static string UsuarioCreado {
            get {
                return ResourceManager.GetString("UsuarioCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se creó correctamente.
        /// </summary>
        internal static string UsuarioCreadoCorrectamente {
            get {
                return ResourceManager.GetString("UsuarioCreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos 8 carácteres(Mayúscula, Letras y Números).
        /// </summary>
        internal static string ValidacionContrasena {
            get {
                return ResourceManager.GetString("ValidacionContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Detalle.
        /// </summary>
        internal static string VerDetalle {
            get {
                return ResourceManager.GetString("VerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vision.
        /// </summary>
        internal static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }

        internal static string CampoNombreVacio
        {
            get
            {
                return ResourceManager.GetString("CampoNombreVacio", resourceCulture);
            }
        }

        internal static string msjADirFacVacio
        {
            get
            {
                return ResourceManager.GetString("msjADirFacVacio", resourceCulture);
            }
        }

        internal static string msjADirEnvVacio
        {
            get
            {
                return ResourceManager.GetString("msjADirEnvVacio", resourceCulture);
            }
        }

        internal static string msjAVerifiquePass
        {
            get
            {
                return ResourceManager.GetString("msjAVerifiquePass", resourceCulture);
            }
        }

        internal static string msjCampoVacio
        {
            get
            {
                return ResourceManager.GetString("msjCampoVacio", resourceCulture);
            }
        }

        internal static string Desde
        {
            get
            {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }

        internal static string Hasta
        {
            get
            {
                return ResourceManager.GetString("Hasta", resourceCulture);
            }
        }

        internal static string Remito
        {
            get
            {
                return ResourceManager.GetString("Remito", resourceCulture);
            }
        }

        internal static string Registrar
        {
            get
            {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }

        internal static string Agregar
        {
            get
            {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        internal static string AdqCreada
        {
            get
            {
                return ResourceManager.GetString("AdqCreada", resourceCulture);
            }
        }
        
    }
}
